//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Generated by z64rasm
        ///; commit: e51ec4d8c689797e1f49b2b395fb22342450fb42
        ///10,4a14b85f
        ///14,6e5483d
        ///20580,3800000
        ///20584,3830000
        ///20588,3800000
        ///2058c,0
        ///20590,0
        ///20594,0
        ///20598,0
        ///2059c,0
        ///205a0,0
        ///205a4,0
        ///205a8,0
        ///205ac,0
        ///205b0,0
        ///205b4,0
        ///205b8,0
        ///205bc,0
        ///205c0,0
        ///205c4,0
        ///205c8,0
        ///205cc,0
        ///205d0,0
        ///205d4,0
        ///205d8,0
        ///205dc,0
        ///205e0,0
        ///205e4,0
        ///205e8,0
        ///205ec,0
        ///b66b6c,c1d4177
        ///b66b70,8463f6a6
        ///b66b78,0
        ///b66ba8,1000001f
        ///b66bac,0
        ///b66c28,c1d4177
        ///b66c2c,8463f6a6
        ///b66d10,c1d4177
        ///b66d14,8723f6a6
        ///b66d1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ASM_PATCH {
            get {
                return ResourceManager.GetString("ASM_PATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;DPAD_CONFIG&quot;: &quot;038037F4&quot;,
        ///    &quot;DPAD_TEXTURE&quot;: &quot;03803B40&quot;,
        ///    &quot;G_C_HEAP&quot;: &quot;03828000&quot;,
        ///    &quot;G_PAYLOAD_ADDR&quot;: &quot;03800000&quot;,
        ///    &quot;HASH_ICONS&quot;: &quot;03803880&quot;,
        ///    &quot;HUD_COLOR_CONFIG&quot;: &quot;03803910&quot;,
        ///    &quot;MISC_CONFIG&quot;: &quot;03803968&quot;,
        ///    &quot;PAYLOAD_END&quot;: &quot;03804B40&quot;,
        ///    &quot;PAYLOAD_START&quot;: &quot;03800000&quot;,
        ///    &quot;SAVE_FILE_CONFIG&quot;: &quot;03803984&quot;,
        ///    &quot;dpad_sprite&quot;: &quot;03803900&quot;,
        ///    &quot;g_external_effects&quot;: &quot;03803810&quot;,
        ///    &quot;heap_next&quot;: &quot;038039BC&quot;,
        ///    &quot;setup_db&quot;: &quot;038038D8&quot;
        ///}
        ///.
        /// </summary>
        public static string ASM_SYMBOLS {
            get {
                return ResourceManager.GetString("ASM_SYMBOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -actor
        ///-obj
        ///-vars - todo: may connect to switches
        ///-type - 0=ground, 1=water, 2=air, 3=other, 4=respawn
        ///-moving - 0=no, 1=yes
        ///-scene excludes
        ///-octorok
        ///0008
        ///0005
        ///ff00
        ///1
        ///0
        ///13,49
        ///-wallmaster
        ///000a
        ///0009
        ///0001
        ///0
        ///1
        ///
        ///-dodongo
        ///000b
        ///000a
        ///0001,0000
        ///0
        ///1
        ///
        ///-keese
        ///000c
        ///000b
        ///8003,0004,0000
        ///2
        ///1
        ///
        ///-tektite
        ///0012
        ///0012
        ///fffd,fffe,ffff
        ///0
        ///1
        ///
        ///-peahat
        ///0014
        ///0014
        ///0000
        ///0
        ///1
        ///7
        ///-dinolfos
        ///0019
        ///0017
        ///0000
        ///0
        ///1
        ///1b,21,60,66
        ///-shabom
        ///001d
        ///000e
        ///0000
        ///2
        ///1
        ///69
        ///-skulltula
        ///0024
        ///0020
        ///003f,007f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ENEMIES {
            get {
                return ResourceManager.GetString("ENEMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mmr_f_sot {
            get {
                object obj = ResourceManager.GetObject("mmr_f_sot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -version 13
        ///- Deku Mask
        ///
        ///
        ///0
        ///0
        ///- Hero&apos;s Bow
        ///104
        ///10;0,120;0,129
        ///0
        ///0
        ///- Fire Arrow
        ///107
        ///2,92,120,433;2,93,120,433;10,92,433;10,93;92,119,433,434;92,93,119,433,435
        ///0
        ///0
        ///- Ice Arrow
        ///112,139,10,93
        ///
        ///0
        ///0
        ///- Light Arrow
        ///116
        ///4,120,436,433;25,119,437
        ///0
        ///0
        ///- Bomb Bag (20)
        ///
        ///
        ///0
        ///0
        ///- Magic Bean
        ///103,0
        ///
        ///0
        ///0
        ///- Powder Keg
        ///106,2,92,120,433
        ///
        ///0
        ///0
        ///- Pictobox
        ///
        ///444;447
        ///0
        ///0
        ///- Lens of Truth
        ///106
        ///9,433;95
        ///0
        ///0
        ///- Hookshot
        ///111
        ///92,120;0,92,433;10,120;0,10,433
        ///0
        ///0
        ///- Great Fairy Magic Meter
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string REQ_CASUAL {
            get {
                return ResourceManager.GetString("REQ_CASUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -version 13
        ///- Deku Mask
        ///
        ///
        ///0
        ///0
        ///- Hero&apos;s Bow
        ///104
        ///0,129;435,444,445;10;0,120;119,120,444;120,270;129,270;119,270
        ///0
        ///0
        ///- Fire Arrow
        ///107
        ///119,441;93,119,440;2,120,433;435,444,445;10;270
        ///0
        ///0
        ///- Ice Arrow
        ///112,139,438
        ///435,444,445;92,445;93;119,270,445
        ///0
        ///0
        ///- Light Arrow
        ///116,442
        ///4,120,433;0,25,92,93,101,443;25,92,119;10,435,444;25,92,101,270,443;435,444,445
        ///0
        ///0
        ///- Bomb Bag (20)
        ///
        ///
        ///0
        ///0
        ///- Magic Bean
        ///103
        ///
        ///0
        ///0
        ///- Powder Keg
        ///92,106
        ///119,444,445;120;108;173,270,436
        ///0
        ///0
        ///- Pictobox
        ///436
        ///16; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string REQ_GLITCH {
            get {
                return ResourceManager.GetString("REQ_GLITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-terminafield
        ///0
        ///3
        ///2
        ///mm-snowhead
        ///0,1
        ///15
        ///13
        ///mm-greatbay
        ///0,1
        ///1d
        ///10
        ///mm-ikanacanyon
        ///0,1
        ///1e
        ///11
        ///mm-swamp
        ///0,1
        ///1c
        ///c
        ///mm-clocktown1
        ///1
        ///19
        ///15
        ///mm-clocktown2
        ///1
        ///19
        ///16
        ///mm-clocktown3
        ///1
        ///19
        ///17
        ///mm-goronshrine
        ///1
        ///26
        ///30
        ///mm-romaniranch
        ///1
        ///7
        ///2f
        ///mm-zorahall
        ///1
        ///b
        ///36
        ///mm-dekupalace
        ///1
        ///19
        ///12
        ///mm-caves
        ///2
        ///1a
        ///3b
        ///mm-snowheadtemple
        ///2
        ///15
        ///65
        ///mm-greatbaytemple
        ///2
        ///16
        ///66
        ///mm-piratefortress
        ///2,0
        ///3
        ///14
        ///mm-ikanacastle
        ///2,0
        ///21
        ///6f
        ///mm-stonetower
        ///2
        ///19
        ///6
        ///mm-invertedstonetower
        ///2
        ///19
        ///7
        ///mm-w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SEQS {
            get {
                return ResourceManager.GetString("SEQS", resourceCulture);
            }
        }
    }
}
