//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMRando.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMRando.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -actor
        ///-obj
        ///-vars - todo: may connect to switches
        ///-type- 0=ground, 1=water, 2=air, 3=other
        ///-moving 0=no, 1=yes
        ///-octorok
        ///0008
        ///0005
        ///ff00
        ///1
        ///0
        ///-wallmaster
        ///000a
        ///0009
        ///0001
        ///3
        ///0
        ///-dodongo
        ///000b
        ///000a
        ///0001,0000
        ///0
        ///1
        ///-keese
        ///000c
        ///000b
        ///8003,0004,0000
        ///2
        ///1
        ///-tektite
        ///0012
        ///0012
        ///fffd,fffe
        ///0
        ///1
        ///-peahat
        ///-0014
        ///-0014
        ///-0000
        ///-3
        ///-0
        ///-dinolfos
        ///0019
        ///0017
        ///0000
        ///0
        ///1
        ///-shabom
        ///001d
        ///000e
        ///0000
        ///2
        ///1
        ///-skulltula
        ///0024
        ///0020
        ///003f,007f,0004
        ///3
        ///0
        ///-death armos
        ///002d
        ///001d
        ///0003,0001,0002,0004,0007
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENEMIES {
            get {
                return ResourceManager.GetString("ENEMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a new file;a quest&apos;s inception
        ///a woodland spirit
        ///Woodfall Temple;the sleeping temple
        ///a projectile;a ranged weapon
        ///Snowhead Temple;an icy gale
        ///the power of fire;a magical item
        ///Great Bay Temple;the ocean temple
        ///the power of ice;a magical item
        ///Stone Tower Temple;the cursed temple
        ///the power of light;a magical item
        ///a town shop
        ///an item carrier;a vessel of explosives
        ///a hidden merchant;a gorging merchant
        ///a plant seed
        ///a large goron
        ///gunpowder;a dangerous item;an explosive barrel
        ///a witch
        ///a light recor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GOSSIP {
            get {
                return ResourceManager.GetString("GOSSIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -deku mask
        ///78
        ///-items (fix bottles?)
        ///22
        ///25
        ///26
        ///27
        ///1b
        ///35
        ///34
        ///43
        ///42
        ///41
        ///3b
        ///59
        ///60
        ///6a
        ///5a
        ///5a
        ///6f
        ///50
        ///-upgrades
        ///38
        ///39
        ///33
        ///23
        ///24
        ///1c
        ///1d
        ///8
        ///9
        ///-trade items
        ///96
        ///97
        ///98
        ///99
        ///9a
        ///a0
        ///aa
        ///ab
        ///a1
        ///-notebook hps (fix)
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///-other hp (fix)
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///c
        ///-mask
        ///84
        ///7e
        ///8d
        ///8b
        ///86
        ///80
        ///8c
        ///7f
        ///88
        ///8e
        ///82
        ///83
        ///8f
        ///85
        ///8a
        ///89
        ///87
        ///81
        ///7c
        ///7d
        ///79
        ///7a
        ///-songs (fix)
        ///50
        ///50
        ///50
        ///50
        ///50
        ///50
        ///50
        ///50
        ///-keysanity (fix)
        ///3e
        ///3f
        ///3d
        ///3c
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ITEM_INDICES {
            get {
                return ResourceManager.GetString("ITEM_INDICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///0
        ///0
        ///99,124
        ///
        ///0
        ///0
        ///102,115,128,129
        ///5;24;25;70
        ///0
        ///0
        ///107,115,134
        ///
        ///0
        ///0
        ///111,115,114,138,139
        ///
        ///0
        ///0
        ///
        ///
        ///0
        ///0
        ///98,0
        ///
        ///0
        ///0
        ///101,2,88
        ///
        ///0
        ///0
        ///98
        ///
        ///0
        ///0
        ///101
        ///
        ///0
        ///0
        ///106
        ///88,1;88,0;10,1;10,0;88,22;88,23;10,22;10,23
        ///0
        ///0
        ///112,72
        ///
        ///0
        ///0
        ///
        ///
        ///0
        ///0
        ///104,115
        ///
        ///0
        ///2
        ///103,7
        ///
        ///15
        ///0
        ///106,10
        ///
        ///0
        ///0
        ///109,86
        ///
        ///0
        ///32
        ///36,78
        ///
        ///0
        ///32
        ///
        ///0;89;1;22;23;10
        ///0
        ///0
        ///------------------------
        ///101,26
        ///2;168
        ///0
        ///12
        ///101,13
        ///2;12,168;14,168;15,168;16,168;17,168
        ///0
        ///48
        ///110
        ///5,163,84,6;24,163,84,6;25,163,84,6;1,2, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REQ_CASUAL {
            get {
                return ResourceManager.GetString("REQ_CASUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///0
        ///0
        ///99
        ///5;24;25;10;124
        ///0
        ///0
        ///102
        ///5;24;25
        ///0
        ///0
        ///107,115,134
        ///
        ///0
        ///0
        ///111,114,138,139
        ///
        ///0
        ///0
        ///
        ///
        ///0
        ///0
        ///98
        ///
        ///0
        ///0
        ///101
        ///2;12;13;14;15;16;17
        ///0
        ///0
        ///
        ///12;13;14;15;16;17
        ///0
        ///0
        ///101
        ///
        ///0
        ///0
        ///106
        ///0;1;22;23
        ///0
        ///0
        ///112,72
        ///
        ///0
        ///0
        ///
        ///
        ///0
        ///0
        ///104,115
        ///
        ///0
        ///2
        ///103,88
        ///
        ///15
        ///0
        ///106,10
        ///
        ///0
        ///0
        ///109
        ///
        ///0
        ///32
        ///36
        ///5;78;24;25
        ///0
        ///32
        ///
        ///0;89;1;22;23;10
        ///0
        ///0
        ///------------------------
        ///101,26
        ///2;12;13;14;15;16;17
        ///0
        ///12
        ///101,13
        ///2;12;14;15;16;17
        ///0
        ///48
        ///110
        ///1,2,10;22,2,10;23,2,10;1,2,89;22,2,89;23,2,89;1,2,4;22,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REQ_GLITCH {
            get {
                return ResourceManager.GetString("REQ_GLITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-terminafield
        ///0
        ///3
        ///2
        ///mm-snowhead
        ///0,1
        ///15
        ///13
        ///mm-greatbay
        ///0,1
        ///1d
        ///10
        ///mm-ikanacanyon
        ///0,1
        ///1e
        ///11
        ///mm-swamp
        ///0,1
        ///1c
        ///c
        ///mm-clocktown1
        ///1
        ///19
        ///15
        ///mm-clocktown2
        ///1
        ///19
        ///16
        ///mm-clocktown3
        ///1
        ///19
        ///17
        ///mm-goronshrine
        ///1
        ///26
        ///30
        ///mm-romaniranch
        ///1
        ///7
        ///2f
        ///mm-zorahall
        ///1
        ///b
        ///36
        ///mm-dekupalace
        ///1
        ///19
        ///12
        ///mm-caves
        ///2
        ///1a
        ///3b
        ///mm-snowheadtemple
        ///2
        ///15
        ///65
        ///mm-greatbaytemple
        ///2
        ///16
        ///66
        ///mm-piratefortress
        ///2,0
        ///3
        ///14
        ///mm-ikanacastle
        ///2,0
        ///21
        ///6f
        ///mm-stonetower
        ///2
        ///19
        ///6
        ///mm-invertedstonetower
        ///2
        ///19
        ///7
        ///mm-w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEQS {
            get {
                return ResourceManager.GetString("SEQS", resourceCulture);
            }
        }
    }
}
