//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMRando.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMRando.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -actor
        ///-obj
        ///-vars - todo: may connect to switches
        ///-type - 0=ground, 1=water, 2=air, 3=other, 4=respawn
        ///-moving - 0=no, 1=yes
        ///-scene excludes
        ///-octorok
        ///0008
        ///0005
        ///ff00
        ///1
        ///0
        ///13,49
        ///-wallmaster
        ///000a
        ///0009
        ///0001
        ///0
        ///1
        ///
        ///-dodongo
        ///000b
        ///000a
        ///0001,0000
        ///0
        ///1
        ///
        ///-keese
        ///000c
        ///000b
        ///8003,0004,0000
        ///2
        ///1
        ///
        ///-tektite
        ///0012
        ///0012
        ///fffd,fffe,ffff
        ///0
        ///1
        ///
        ///-peahat
        ///0014
        ///0014
        ///0000
        ///0
        ///1
        ///7
        ///-dinolfos
        ///0019
        ///0017
        ///0000
        ///0
        ///1
        ///
        ///-shabom
        ///001d
        ///000e
        ///0000
        ///2
        ///1
        ///69
        ///-skulltula
        ///0024
        ///0020
        ///003f,007f,0004
        ///3
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENEMIES {
            get {
                return ResourceManager.GetString("ENEMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -version 5
        ///- Deku Mask
        ///
        ///
        ///0
        ///0
        ///- Hero&apos;s Bow
        ///100
        ///10;0,116;0,125
        ///0
        ///0
        ///- Fire Arrow
        ///103
        ///2,88,116;2,89,116;10,88;88,89,115,129;88,89,115,130;88,89,115,131;88,115,129,130;88,115,129,131;88,115,130,131;10,89
        ///0
        ///0
        ///- Ice Arrow
        ///108,135,10,89
        ///
        ///0
        ///0
        ///- Light Arrow
        ///112
        ///4,116,139;4,116,140;4,116,141;4,116,142;21,88,89,115,139,140,0;21,88,89,115,139,141,0;21,88,89,115,139,142,0;21,88,89,115,140,141,0;21,88,89,115,140,142,0;21,88,89,115,141,142,0
        ///0
        ///0
        ///- Bomb Bag (20)
        ///
        ///
        ///0
        ///0
        ///- Magic Bean
        ///99,0
        ///
        ///0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REQ_CASUAL {
            get {
                return ResourceManager.GetString("REQ_CASUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -version 5
        ///- Deku Mask
        ///
        ///
        ///0
        ///0
        ///- Hero&apos;s Bow
        ///100
        ///5;24;25;10;125
        ///0
        ///0
        ///- Fire Arrow
        ///103
        ///5;24;25
        ///0
        ///0
        ///- Ice Arrow
        ///108,116,135
        ///
        ///0
        ///0
        ///- Light Arrow
        ///112,115,139,140
        ///
        ///0
        ///0
        ///- Bomb Bag (20)
        ///
        ///
        ///0
        ///0
        ///- Magic Bean
        ///99
        ///
        ///0
        ///0
        ///- Powder Keg
        ///102
        ///2;12;13;210;15;16;17
        ///0
        ///0
        ///- Pictobox
        ///
        ///12;13;210;15;16;17
        ///0
        ///0
        ///- Lens of Truth
        ///102
        ///
        ///0
        ///0
        ///- Hookshot
        ///107
        ///0;1;22;23
        ///0
        ///0
        ///- Great Fairy&apos;s Sword
        ///113,112,114,72
        ///
        ///0
        ///0
        ///- Witch Bottle
        ///
        ///
        ///0
        ///0
        ///- Aliens Bottle
        ///105,116
        ///
        ///0
        ///2
        ///- Gold Dust
        ///104, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REQ_GLITCH {
            get {
                return ResourceManager.GetString("REQ_GLITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-terminafield
        ///0
        ///3
        ///2
        ///mm-snowhead
        ///0,1
        ///15
        ///13
        ///mm-greatbay
        ///0,1
        ///1d
        ///10
        ///mm-ikanacanyon
        ///0,1
        ///1e
        ///11
        ///mm-swamp
        ///0,1
        ///1c
        ///c
        ///mm-clocktown1
        ///1
        ///19
        ///15
        ///mm-clocktown2
        ///1
        ///19
        ///16
        ///mm-clocktown3
        ///1
        ///19
        ///17
        ///mm-goronshrine
        ///1
        ///26
        ///30
        ///mm-romaniranch
        ///1
        ///7
        ///2f
        ///mm-zorahall
        ///1
        ///b
        ///36
        ///mm-dekupalace
        ///1
        ///19
        ///12
        ///mm-caves
        ///2
        ///1a
        ///3b
        ///mm-snowheadtemple
        ///2
        ///15
        ///65
        ///mm-greatbaytemple
        ///2
        ///16
        ///66
        ///mm-piratefortress
        ///2,0
        ///3
        ///14
        ///mm-ikanacastle
        ///2,0
        ///21
        ///6f
        ///mm-stonetower
        ///2
        ///19
        ///6
        ///mm-invertedstonetower
        ///2
        ///19
        ///7
        ///mm-w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEQS {
            get {
                return ResourceManager.GetString("SEQS", resourceCulture);
            }
        }
    }
}
